/**
 * report.ts — turn a 2,200-word evaluation into what a job seeker needs.
 *
 * The reports are structured A–G plus a machine-summary YAML fence, a score
 * breakdown, extracted ATS keywords and a cover-letter draft. That is the right
 * shape for an agent and the wrong shape for a person deciding whether to spend
 * an evening applying.
 *
 * Someone reading this wants four things, in this order:
 *   1. Should I bother?          -> the verdict
 *   2. Why does it fit me?       -> the match
 *   3. What is weak?             -> the gaps, stated honestly
 *   4. What would they ask me?   -> interview prep
 *
 * Everything else — YAML, keyword lists, legitimacy signal tables — is
 * machinery. It stays available but does not lead.
 */

export interface ReportSection {
  id: string;
  title: string;
  body: string;
}

export interface ParsedReport {
  /** One-line verdict pulled from the header or the Verdict section. */
  verdict: string | null;
  /** Sections a human wants, in reading order. */
  primary: ReportSection[];
  /** Machinery — available, collapsed by default. */
  secondary: ReportSection[];
  /** True for the short triage format (no A–G blocks). */
  isTriage: boolean;
}

/** Headings a person actually wants, mapped to plain titles. */
const PRIMARY: Record<string, string> = {
  'verdict': 'Verdict',
  'a) role summary': 'What the job is',
  'b) match with cv': 'Why you fit',
  "why it doesn't fit": "Why it doesn't fit",
  'hard blockers': 'Dealbreakers',
  'c) level and strategy': 'How to pitch yourself',
  'd) comp and demand': 'Pay and demand',
  'f) interview plan': 'What they might ask',
  'better fit at this company': 'Better fit here',
};

/** Machinery: correct to keep, wrong to lead with. */
const SECONDARY: Record<string, string> = {
  'machine summary': 'Raw data',
  'e) customization plan': 'CV tailoring plan',
  'g) posting legitimacy': 'Is this posting real?',
  'risk summary': 'Risk summary',
  'score breakdown': 'How it scored',
  'keywords extracted': 'ATS keywords',
  'cover letter draft': 'Cover letter draft',
};

export function parseReport(markdown: string): ParsedReport {
  const lines = markdown.split('\n');

  const sections: ReportSection[] = [];
  let current: ReportSection | null = null;

  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+?)\s*$/);
    if (h2) {
      if (current) sections.push(current);
      const title = h2[1].trim();
      current = { id: title.toLowerCase(), title, body: '' };
      continue;
    }
    if (current) current.body += line + '\n';
  }
  if (current) sections.push(current);

  const primary: ReportSection[] = [];
  const secondary: ReportSection[] = [];

  for (const s of sections) {
    const key = s.id;
    if (key in PRIMARY) primary.push({ ...s, title: PRIMARY[key] });
    else if (key in SECONDARY) secondary.push({ ...s, title: SECONDARY[key] });
    else secondary.push(s);
  }

  // Preserve the reading order defined above rather than file order.
  const order = Object.values(PRIMARY);
  primary.sort((a, b) => order.indexOf(a.title) - order.indexOf(b.title));

  const verdictSection = sections.find((s) => s.id === 'verdict');
  const verdict = verdictSection
    ? verdictSection.body.trim().split('\n')[0].replace(/^\*\*|\*\*$/g, '').trim()
    : null;

  return {
    verdict,
    primary,
    secondary,
    isTriage: !sections.some((s) => s.id.startsWith('a) ')),
  };
}

/**
 * Minimal markdown -> HTML for report bodies.
 *
 * Deliberately small: reports are generated by our own prompts, so the subset
 * is known. Pulling in a full markdown pipeline for headings, bold, lists and
 * tables would be weight for no benefit.
 */
export function renderMarkdown(md: string): string {
  const esc = (t: string) =>
    t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const inline = (t: string) =>
    esc(t)
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/`(.+?)`/g, '<code class="rounded bg-[var(--color-paper)] px-1 py-0.5 text-[0.9em]">$1</code>')
      .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2" target="_blank" rel="noreferrer" class="text-[var(--color-act)] underline underline-offset-2">$1</a>');

  const out: string[] = [];
  let inTable = false;
  let inList = false;

  const closeList = () => { if (inList) { out.push('</ul>'); inList = false; } };
  const closeTable = () => { if (inTable) { out.push('</tbody></table></div>'); inTable = false; } };

  for (const raw of md.split('\n')) {
    const line = raw.trimEnd();

    if (/^\|[\s-:|]+\|$/.test(line)) continue;           // table separator

    if (line.startsWith('|')) {
      const cells = line.split('|').slice(1, -1).map((c) => inline(c.trim()));
      if (!inTable) {
        closeList();
        out.push('<div class="overflow-x-auto"><table class="w-full text-sm"><tbody>');
        inTable = true;
      }
      out.push('<tr class="border-b border-[var(--color-line)] last:border-0">' +
        cells.map((c) => `<td class="py-2 pr-4 align-top">${c}</td>`).join('') + '</tr>');
      continue;
    }
    closeTable();

    if (/^[-*]\s+/.test(line)) {
      if (!inList) { out.push('<ul class="ml-4 list-disc space-y-1.5">'); inList = true; }
      out.push(`<li>${inline(line.replace(/^[-*]\s+/, ''))}</li>`);
      continue;
    }
    closeList();

    const h3 = line.match(/^###\s+(.+)/);
    if (h3) { out.push(`<h4 class="mt-5 mb-1.5 font-semibold">${inline(h3[1])}</h4>`); continue; }

    if (line.startsWith('> ')) {
      out.push(`<blockquote class="border-l-2 border-[var(--color-line-strong)] pl-3 italic text-[var(--color-ink-soft)]">${inline(line.slice(2))}</blockquote>`);
      continue;
    }

    if (line.startsWith('```')) continue;

    if (line.trim() === '') { out.push(''); continue; }
    out.push(`<p>${inline(line)}</p>`);
  }
  closeList();
  closeTable();
  return out.join('\n');
}
